# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NTU3Yzg1OTAzYTNjNDVkODhkODRjODc2ZDBhOWQzN2E3ZDU5ODBmMzhhNTQwOTljY2FjNWM3YjJmNTFmYjZlNzAyYzRkZDhiYzY1NTI1ZTM3ZGJhMzAxYTVkNjk3ZWEyMzIzYTUzY2NjMWNhMzE3Mzc1NWQzZjZiMzNlMWMxYTM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
