# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZmNkM2VlNTVkZDAzMTBkZGRhM2NjMzc0YmViYTc1NzQ2ZGRjNzYwZmM0ZWMxZDk2ZGMxM2Q1YThjY2U1NTAwNTA4YjIyM2M0MWJmNzkyYzc0YTRlYzFlYzdkZmE0OGRiMWU5OGEzYTJhZjNjNTFmMTgzOWZlMjFlYmJlN2JiM2I=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
