# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MmZjMjYxNDk5YWIxY2JiNzdmYTUxYTM4NzJiYTM3MDBlNjczNzVjMjdhMzA1YjBjNTEyMjg0NTNlZDg2ODQxMjE4MDI2Y2IxOGNlM2JjYzU4NmJjYmQyNWI4MDM4NTZjYTE3ZDc0NDJhNGIxNjA3YTI5ODJhZDhjYjU3M2Y0ODM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
