# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZWJhMzQ3YjgzMTYyOWI1MDVjYjBmOGVmM2Q4NWQwMzFiZmIxNzllOTIwYWIzODhjMGU2OTdkODE3MDI1YzY2NDc3ZjYxYjgyMGIzMTg1OThiMjYxNjgyNWY1Y2M4ZjI3M2QyZGEzMWQyNTdkMjJhMWQxZjg4MmE2MzliNDhkYTk=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
