apiVersion: skaffold/v1
kind: Config
build:
  artifacts:
    - image: zacwastaken/gateway
      context: ../gateway
      jib: {}
    - image: zacwastaken/parking
      context: ../parking
      jib: {}
    - image: zacwastaken/reservations
      context: ../reservations
      jib: {}
    - image: zacwastaken/payments
      context: ../payments
      jib: {}
  tagPolicy:
    envTemplate:
      template: "{{.IMAGE_NAME}}:latest"
deploy:
  kustomize: {}
