# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: MWY4NTBjZjZhNzNkNjBhNjM2MmMyYmExMWViZDJiMjUyZWU5MzdjZWJkODc3OTNkNGUxYmU4ZTNjZThhNzdjYmI5YTFhYzU4YjI4NjY2Njc2MTE0NGZiMDBlMjc4MjI2ZTdiNzQzNGMyOGVmMmY1NDVhMjY3NTBmNDdkYjQzNTg=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
