# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NDk1MWI3NTFmYjAxMWQ1MzVhNWI3OGQyNzM0ZTU3NWZlYjA5ZDM1YTk1MTQ4ZTQxOTJiNzA0OWRjN2EwM2VhOWM2ZWE3YzgwZTI4YmY1Y2IzMGU3NzZiMzFhOGQwZDJmY2U2Y2UwM2U4MDk1NWU3YzFkZWI0OWZhNGM5M2U3YzM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@jhipster-registry:8761/eureka/
